apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: myweb
spec:
  ports:
    - port: 3101
      targetPort: 3101
      protocol: TCP
  selector:
    app: loki

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.5.0
          ports:
            - containerPort: 3101
          volumeMounts:
            - mountPath: /etc/loki/config.yaml  # Mount it as local-config.yaml in the expected path
              name: loki-config
              subPath: loki-config.yaml   # Correctly reference the ConfigMap file
      volumes:
        - name: loki-config
          configMap:
            name: loki-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: myweb
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3101
    ingester:
      chunk_target_size: 1048576
      max_chunk_age: 1h
    limits_config:
      max_streams_per_user: 100000
    volume_enabled: true
    schema_config:
      configs:
        - from: 2020-10-10
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 168h
