apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv
 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/c/k8s-image-cache"  
