apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/MelisaBunjaku19
    targetRevision: HEAD
    path: path/to/rollout
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
