apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: mb2821/todo-backend:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: postgres-configmap
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
