apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webproject-production
  namespace: argocd
spec:
  destination:
    namespace: myweb-production
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/melisabunjaku/WebProject
    path: backend/manifests   
    targetRevision: 'main'  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
